### ISSUE TITLE
when I use weexpack plugin add nat-geolocation command  to add the plugin ,there is something wrong

### ISSUE THREAD

**Issue by am1102** [natjs/weex-nat-geolocation#2]
when I use weexpack plugin add nat-geolocation command to add the plugin ,there is something wrong,
the error code is 
Error: Uh oh!
"D:\Workspaces\Weex\weexant\plugins\nat-geolocation\android\GeolocationModule.java" not found!

but I found the code is in my folder

**Comment by Acathur** [comment]
It will be fixed in 0.1.2

**Comment by acathur** [comment]
It will be fixed in 0.1.2
