### ISSUE TITLE
Not working in IOS 

### ISSUE THREAD

**Issue by sushilparajuli** [natjs/weex-nat-geolocation#4]
Not working in IOS and web version  but working fine on Android

**Comment by acathur** [comment]
Actually, all nat plugins only support Android and iOS at present.
As for the situation you encountered, please provide log info.

**Comment by sushilparajuli** [comment]
Here is the issue I am facing : http://recordit.co/Xp1nVUWcky

**Comment by acathur** [comment]
Add the following code to the '*-Info.plist' file
```xml
<key>NSLocationWhenInUseUsageDescription</key>
<string>reason for using this permission goes here</string>
```

**Comment by acathur** [comment]
Same permission issue [nat-media-image/issues#2](https://github.com/natjs/nat-media-image/issues/2)
